// ZB Suites Baguio - Photo Gallery Data
// Organized by categories based on actual folder structure

const PHOTO_PATHS = [
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/CONFERENCE ROOM 1/CONFERENCE ROOM-24.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/CONFERENCE ROOM 1/CONFERENCE ROOM-26.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/CONFERENCE ROOM 1/CONFERENCE ROOM-28.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/CONFERENCE ROOM 2/CONFERENCE ROOM 1-45.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/CONFERENCE ROOM 2/CONFERENCE ROOM 1-46.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/CONFERENCE ROOM 2/CONFERENCE ROOM 1-47.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/CONFERENCE ROOM 2/CONFERENCE ROOM 1-48.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/CONFERENCE ROOM 2/CONFERENCE ROOM 1-49.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/CONFERENCE ROOM 2/CONFERENCE ROOM 1-50.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/CONFERENCE ROOM 2/CONFERENCE ROOM 1-51.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/CONFERENCE ROOM 2/CONFERENCE ROOM 1-52.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/CONFERENCE ROOM 2/CONFERENCE ROOM 1-53.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/DINING AREA/DINING AREA-05.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/DINING AREA/DINING AREA-06.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/DINING AREA/DINING AREA-07.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/DINING AREA/DINING AREA-08.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/DINING AREA/DINING AREA-09.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/DINING AREA/DINING AREA-10.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/DINING AREA/DINING AREA-11.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/DINING AREA/DINING AREA-12.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/DINING AREA/DINING AREA-13.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/DINING AREA/DINING AREA-14.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/DINING AREA/DINING AREA-15.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/EVENTS/EVENTS-188.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/LOBBY/LOBBY-54.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/LOBBY/LOBBY-56.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/LOBBY/LOBBY-57.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/LOBBY/LOBBY-58.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/LOBBY/LOBBY-59.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/LOBBY/LOBBY-60.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/LOBBY/LOBBY-61.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/LOBBY/LOBBY-62.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/MINI GYM/MINI GYM-1.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/MINI GYM/MINI GYM-2.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/MINI GYM/MINI GYM-3.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/MINI GYM/MINI GYM-4.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/OUTDOOR/OUTDOOR SHOTS-63.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/OUTDOOR/OUTDOOR SHOTS-64.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/OUTDOOR/OUTDOOR SHOTS-65.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/OUTDOOR/OUTDOOR SHOTS-66.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/OUTDOOR/OUTDOOR SHOTS-67.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/OUTDOOR/OUTDOOR SHOTS-68.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/PARKING AREA.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 401B/IMG_0497 (1).jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 401B/IMG_0497.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 401B/ROOM 401B LIGHTENED AND WIDENED.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 401B/ROOM 401B-69.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 401B/ROOM 401B-70.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 401B/ROOM 401B-71.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 401B/ROOM 401B-72.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 401B/ROOM 401B-73.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 401B/ROOM 401B-74.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 401B/ROOM 401B-75.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 401B/ROOM 401B-76.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 601/ROOM 604 WIDENED AND LIGHTENED.png",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 702/ROOM 702 WIDENED AND LIGHTENED.png",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 702/ROOM 702-82.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 702/ROOM 702-83.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 702/ROOM 702-84.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 702/ROOM 702-85.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 702/ROOM 702-86.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 702/ROOM 702-87.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 702/ROOM 702-88.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 706/ROOM 706 WIDER AND LIGHTER.png",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 706/ROOM 706-77.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 706/ROOM 706-78.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 706/ROOM 706-79.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 706/ROOM 706-80.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/ROOM 706/ROOM 706-81.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/SOCIAL AREA 2/SOCIAL AREA 2-140.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/COLOR GRADED/SOCIAL AREA 2/SOCIAL AREA 2-142.jpg",
    "ZHONGKE BOLE PHOTOSHOOT/EDITED WITH GRAPHICS (FOR SOC MED)/BILLIARDS-37.png",
    "ZHONGKE BOLE PHOTOSHOOT/EDITED WITH GRAPHICS (FOR SOC MED)/CONFERENCE ROOM 1-47.png",
    "ZHONGKE BOLE PHOTOSHOOT/EDITED WITH GRAPHICS (FOR SOC MED)/DINING AREA.png",
    "ZHONGKE BOLE PHOTOSHOOT/EDITED WITH GRAPHICS (FOR SOC MED)/MINI GYM.png",
    "ZHONGKE BOLE PHOTOSHOOT/EDITED WITH GRAPHICS (FOR SOC MED)/ROOM 401B-72.png",
    "ZHONGKE BOLE PHOTOSHOOT/IMG_0346.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/IMG_0383.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/IMG_0455.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/IMG_0457.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/IMG_0470.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/IMG_0471.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/IMG_0472.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/BILLIARDS/IMG_0370.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/CONFERENCE ROOM 2/IMG_0421.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/CONFERENCE ROOM 2/IMG_0427.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/DINING AREA/IMG_0378.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/MINI GYM/IMG_0331.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/MINI GYM/IMG_0332.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/MINI GYM/IMG_0333.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/MINI GYM/IMG_0334.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/MINI GYM/IMG_0335.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/MINI GYM/IMG_0336.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/MINI GYM/IMG_0337.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/MINI GYM/IMG_0338.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/ROOM 401B/IMG_0504.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 603/IMG_0473.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 603/IMG_0474.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 603/IMG_0475.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 603/IMG_0476.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 603/IMG_0477.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 603/IMG_0478.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 603/IMG_0479.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 702/IMG_0480.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 702/IMG_0481.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 702/IMG_0482.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 702/IMG_0483.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 702/IMG_0484.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 702/IMG_0485.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 702/IMG_0486.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 706/IMG_0487.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 706/IMG_0488.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 706/IMG_0489.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 706/IMG_0490.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 706/IMG_0491.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 706/IMG_0492.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 706/IMG_0493.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-ROOM 706/IMG_0494.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-SAFETY NECESSITIES/IMG_0323.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-SAFETY NECESSITIES/IMG_0391.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-SOCIAL AREA 1/IMG_0342.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-SOCIAL AREA 1/IMG_0343.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-SOCIAL AREA 1/IMG_0344.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-SOCIAL AREA 1/IMG_0345.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-SOCIAL AREA 2/IMG_0506.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-SOCIAL AREA 2/IMG_0507.JPG",
    "ZHONGKE BOLE PHOTOSHOOT/RAW/X-SOCIAL AREA 2/IMG_0508.JPG"
];

// Organize photos by category based on folder structure
const PHOTO_CATEGORIES = {
    'CONFERENCE ROOM 1': {
        icon: '🏛️',
        description: 'State-of-the-art conference facilities for corporate events',
        photos: []
    },
    'CONFERENCE ROOM 2': {
        icon: '🏛️',
        description: 'Intimate meeting room for small groups',
        photos: []
    },
    'DINING AREA': {
        icon: '🍽️',
        description: 'Elegant dining experience with local cuisine',
        photos: []
    },
    'EVENTS': {
        icon: '🎉',
        description: 'Grand event spaces for weddings and celebrations',
        photos: []
    },
    'LOBBY': {
        icon: '🏨',
        description: 'Grand lobby with modern Filipino design',
        photos: []
    },
    'MINI GYM': {
        icon: '💪',
        description: 'Fully-equipped fitness center for wellness',
        photos: []
    },
    'OUTDOOR': {
        icon: '🌳',
        description: 'Breathtaking views and garden spaces',
        photos: []
    },
    'PARKING AREA': {
        icon: '🅿️',
        description: 'Secure and spacious parking facility',
        photos: []
    },
    'ROOM 401B': {
        icon: '🛏️',
        description: 'Luxurious Deluxe Room with mountain view',
        photos: []
    },
    'ROOM 601': {
        icon: '🛏️',
        description: 'Premium Standard Room',
        photos: []
    },
    'ROOM 702': {
        icon: '🛏️',
        description: 'Executive Suite with panoramic views',
        photos: []
    },
    'ROOM 706': {
        icon: '🛏️',
        description: 'Luxury Suite with modern amenities',
        photos: []
    },
    'SOCIAL AREA 2': {
        icon: '🎮',
        description: 'Relaxation and entertainment zone',
        photos: []
    },
    'BILLIARDS': {
        icon: '🎱',
        description: 'Recreation area with billiards table',
        photos: []
    }
};

// Sort photos into categories based on path
PHOTO_PATHS.forEach(path => {
    const upperPath = path.toUpperCase();
    
    if (upperPath.includes('CONFERENCE ROOM 1')) {
        PHOTO_CATEGORIES['CONFERENCE ROOM 1'].photos.push(path);
    } else if (upperPath.includes('CONFERENCE ROOM 2')) {
        PHOTO_CATEGORIES['CONFERENCE ROOM 2'].photos.push(path);
    } else if (upperPath.includes('DINING AREA')) {
        PHOTO_CATEGORIES['DINING AREA'].photos.push(path);
    } else if (upperPath.includes('EVENTS')) {
        PHOTO_CATEGORIES['EVENTS'].photos.push(path);
    } else if (upperPath.includes('LOBBY')) {
        PHOTO_CATEGORIES['LOBBY'].photos.push(path);
    } else if (upperPath.includes('MINI GYM')) {
        PHOTO_CATEGORIES['MINI GYM'].photos.push(path);
    } else if (upperPath.includes('OUTDOOR')) {
        PHOTO_CATEGORIES['OUTDOOR'].photos.push(path);
    } else if (upperPath.includes('PARKING')) {
        PHOTO_CATEGORIES['PARKING AREA'].photos.push(path);
    } else if (upperPath.includes('ROOM 401B') || upperPath.includes('401B')) {
        PHOTO_CATEGORIES['ROOM 401B'].photos.push(path);
    } else if (upperPath.includes('ROOM 601') || upperPath.includes('601')) {
        PHOTO_CATEGORIES['ROOM 601'].photos.push(path);
    } else if (upperPath.includes('ROOM 702') || upperPath.includes('702')) {
        PHOTO_CATEGORIES['ROOM 702'].photos.push(path);
    } else if (upperPath.includes('ROOM 706') || upperPath.includes('706')) {
        PHOTO_CATEGORIES['ROOM 706'].photos.push(path);
    } else if (upperPath.includes('SOCIAL AREA 2') || upperPath.includes('SOCIAL AREA 2')) {
        PHOTO_CATEGORIES['SOCIAL AREA 2'].photos.push(path);
    } else if (upperPath.includes('BILLIARDS')) {
        PHOTO_CATEGORIES['BILLIARDS'].photos.push(path);
    }
});

// Remove empty categories
for (const category in PHOTO_CATEGORIES) {
    if (PHOTO_CATEGORIES[category].photos.length === 0) {
        delete PHOTO_CATEGORIES[category];
    }
}

// Export for use in other files
if (typeof window !== 'undefined') {
    window.PHOTO_PATHS = PHOTO_PATHS;
    window.PHOTO_CATEGORIES = PHOTO_CATEGORIES;
}